name: Another thing

on:
#   pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - run: echo yo
#       - name: Save PR number
#         env:
#           PR_NUMBER: ${{ github.event.number }} 
#         run: |
#           mkdir -p ./pr
#           echo $PR_NUMBER > ./pr/pr_number
#       - uses: actions/upload-artifact@v2
#         with:
#           name: pr_number
#           path: pr/
