

on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - run: |
        echo it was issue
      if: github.event.issue
    - run: |
        echo it was pr
      if: github.event.pull_request
