on:
  pull_request_target:
    types:
      - review_requested

permissions:
  contents: read

jobs:
  request_doc_review:
    runs-on: ubuntu-latest
    steps: 
    - run: echo $REV
      env:
        REV: ${{ github.event.requested_team.name }}
