on:
  workflow_run:
    workflows: ["Manually triggered workflow"]
    types: [requested, completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
