on:
  workflow_run:
    workflows: ["Manually triggered workflow"]
    types: [requested]
    branches: [test]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'It was a success'
