name: PR branch

on:
  pull_request:
    types:
      - opened
    branches:    
      - 'releases/**'

jobs:
  a:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo hi
