name: PR cond branch

on:
  pull_request:
    types:
      - opened
jobs:
  run-if:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'releases/'"
