name: "On PR TARGET"

on:
  pull_request_target:
    types:
      - labeled
jobs:
  run_if:
    runs-on: ubuntu-latest
    steps:
      - run: echo "What is on main 2"
      - name: comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR --add-label 'invalid'
          gh pr comment $PR --body 'yo 2'

