name: push_tag

# on:
#   push:
#     tags:
#       - run_workflow
#       - run_workflow*
#       - v1*
#       - v2.*
#       - v3**
on:
  push:
    tags:
      - '**'


jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
