name: "TEST"

on:
  push:
    branches:    
      - 'main'
      - 'releases/**'
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'A review from octo-team was requested'
