name: "PR review request"

on:
  pull_request:
    types: [review_requested]
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: >
      ${{ contains(github.event.pull_request.requested_reviewers.*.login, 'octo-org/octo-team') }}
    steps:
      - run: echo 'A review from octo-team was requested'

  always:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - if: ${{ github.event.requested_reviewer.login == 'sketest'}}
        run: echo sketest
      - if: ${{ github.event.requested_reviewer.login == 'me'}}
        run: echo me
