on:
  pull_request_target:
    paths:
      - '.github/workflows/**'
      - '.github/CODEOWNERS'
      - 'package*.json'

jobs:
  triage:
    if: >-
      ${{
        github.event.pull_request.user.login != 'octobot' &&
        github.event.pull_request.user.login != 'dependabot[bot]'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: "Comment about changes we can't accept"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh issue edit $PR_NUMBER --add-label "invalid"
          gh issue comment $PR_NUMBER "It looks like you edited `package*.json`, `.github/CODEOWNERS`, or `.github/workflows/**'`. We don't allow contributions to these files. Please review our [contributing guidelines](https://github.com/octo-org/octo-repo/blob/main/CONTRIBUTING.md) for what contributions are accepted."
