on:
  push:

# jobs:
#   a:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Run a one-line script
#         run: echo hi

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
