name: Use the data

on:
  workflow_run:
    workflows: [Upload data, Another thing]
    types:
      - requested

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
      - run: echo ${{ github.event.workflow_run.event }}
#       - name: View context attributes
#         uses: actions/github-script@v5
#         with:
#           script: |
#             console.log(context)
#       - name: 'Download artifact'
#         uses: actions/github-script@v5
#         with:
#           script: |
#             let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                run_id: context.payload.workflow_run.id,
#             });
#             let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
#               return artifact.name == "pr_number"
#             })[0];
#             let download = await github.rest.actions.downloadArtifact({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                artifact_id: matchArtifact.id,
#                archive_format: 'zip',
#             });
#             var fs = require('fs');
#             fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

#       - name: 'Unzip artifact'
#         run: unzip pr_number.zip

#       - name: 'Comment on PR'
#         uses: actions/github-script@v5
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             var fs = require('fs');
#             var issue_number = Number(fs.readFileSync('./pr_number'));
#             await github.rest.issues.createComment({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: issue_number,
#               body: 'Thank you for the PR!'
#             });
