name: Use the data

on:
  workflow_run:
    workflows: ["Upload data"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.workflow_run.id }}
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log("start")
            let allArtifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            console.log(allArtifacts)
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            console.log(matchArtifact)
            console.log(matchArtifact.id)
            let download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr_number.zip', Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip pr_number.zip

      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./pr_number'));
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Thank you for the PR!'
            });
