name: "TRIG"

#   workflow_dispatch:

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
